<?php
/**
 * Plugin Name: DemoPress Agent
 * Description: Golden-template export, readiness and disposable-demo login bridge for DemoPress.
 * Version: 1.0.0
 * Author: DemoPress
 */
if(!defined('ABSPATH'))exit;
const DEMOPRESS_AGENT_VERSION='1.0.0';
function demopress_mode(){if(defined('DEMOPRESS_MODE'))return (string)DEMOPRESS_MODE;$e=getenv('DEMOPRESS_MODE');return $e?:'template';}
function demopress_template_mode(){return demopress_mode()==='template';}
function demopress_saved_secret(){return (string)get_option('demopress_agent_secret','');}
function demopress_env_secret(){if(defined('DEMOPRESS_INTERNAL_TEMPLATE_TOKEN'))return (string)DEMOPRESS_INTERNAL_TEMPLATE_TOKEN;return (string)(getenv('INTERNAL_TEMPLATE_TOKEN')?:'');}
function demopress_expected_secret(){return demopress_saved_secret()?:demopress_env_secret();}
function demopress_auth($request){$a=demopress_expected_secret();$b=(string)$request->get_header('X-DemoPress-Template-Token');return $a!==''&&$b!==''&&hash_equals($a,$b);}
function demopress_direct_auth(){ $a=demopress_expected_secret();$b=(string)($_SERVER['HTTP_X_DEMOPRESS_TEMPLATE_TOKEN']??'');return $a!==''&&$b!==''&&hash_equals($a,$b);}
add_action('admin_menu',function(){add_options_page('DemoPress Agent','DemoPress Agent','manage_options','demopress-agent','demopress_settings_page');});
add_action('admin_init',function(){if(!current_user_can('manage_options')||empty($_POST['demopress_agent_save']))return;check_admin_referer('demopress_agent_save');$action=sanitize_key($_POST['secret_action']??'keep');if($action==='clear')delete_option('demopress_agent_secret');elseif($action==='generate')update_option('demopress_agent_secret',bin2hex(random_bytes(32)),false);elseif($action==='replace'&&!empty($_POST['demopress_agent_secret']))update_option('demopress_agent_secret',sanitize_text_field(wp_unslash($_POST['demopress_agent_secret'])),false);wp_safe_redirect(admin_url('options-general.php?page=demopress-agent&updated=1'));exit;});
function demopress_settings_page(){if(!current_user_can('manage_options'))return;$saved=demopress_saved_secret();$env=demopress_env_secret();$effective=demopress_expected_secret();$source=$saved?'Saved in WordPress':($env?'Environment / wp-config':'None');?><div class="wrap"><h1>DemoPress Agent</h1><p>Agent version <strong><?php echo esc_html(DEMOPRESS_AGENT_VERSION);?></strong></p><table class="widefat striped" style="max-width:760px"><tbody><tr><td><strong>Mode</strong></td><td><?php echo esc_html(demopress_mode());?></td></tr><tr><td><strong>Secret key</strong></td><td><?php if($effective):?><span style="color:#16803a;font-weight:700">✓ Secret key saved</span><br><code><?php echo esc_html(substr(hash('sha256',$effective),0,12));?>…</code><br><small>Source: <?php echo esc_html($source);?>. The key itself is never displayed.</small><?php else:?><span style="color:#b32d2e;font-weight:700">No secret key configured</span><?php endif;?></td></tr></tbody></table><h2>Secret key</h2><form method="post"><?php wp_nonce_field('demopress_agent_save');?><input type="hidden" name="demopress_agent_save" value="1"><p><label><input type="radio" name="secret_action" value="keep" checked> Keep current key</label></p><p><label><input type="radio" name="secret_action" value="replace"> Replace with: <input type="password" name="demopress_agent_secret" autocomplete="new-password" style="width:420px"></label></p><p><label><input type="radio" name="secret_action" value="generate"> Generate a new 64-character key</label></p><p><label><input type="radio" name="secret_action" value="clear"> Clear saved WordPress key (environment key, if present, becomes effective)</label></p><p class="submit"><button class="button button-primary">Save DemoPress Agent settings</button></p></form><p><strong>Recommended:</strong> use the same secret as <code>INTERNAL_TEMPLATE_TOKEN</code> on the launcher. Environment configuration remains supported for automated deployments.</p></div><?php }
add_action('admin_notices',function(){if(demopress_template_mode())echo '<div class="notice notice-info"><p><strong>DemoPress Template Site.</strong> Finish your changes, then publish a snapshot from DemoPress Manager. Agent secret status is available under Settings → DemoPress Agent.</p></div>';});
function demopress_plugins(){require_once ABSPATH.'wp-admin/includes/plugin.php';$a=[];foreach(get_plugins() as $f=>$d)$a[]=['file'=>$f,'name'=>$d['Name']??'','version'=>$d['Version']??'','active'=>is_plugin_active($f)];return $a;}function demopress_themes(){$a=[];foreach(wp_get_themes() as $s=>$t)$a[]=['slug'=>$s,'name'=>$t->get('Name'),'version'=>$t->get('Version'),'active'=>get_stylesheet()===$s];return $a;}
add_action('rest_api_init',function(){register_rest_route('demopress-agent/v1','/status',['methods'=>'GET','permission_callback'=>'demopress_auth','callback'=>function(){return ['ok'=>true,'agentVersion'=>DEMOPRESS_AGENT_VERSION,'mode'=>demopress_mode(),'secretConfigured'=>demopress_expected_secret()!=='','wordpress'=>get_bloginfo('version'),'activeTheme'=>get_stylesheet(),'themeVersion'=>wp_get_theme()->get('Version'),'plugins'=>demopress_plugins(),'themes'=>demopress_themes(),'db'=>true,'site'=>home_url('/'),'exportProtocol'=>2,'exportMode'=>'stream'];}]);register_rest_route('demopress-agent/v1','/ready',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>function(){return ['ready'=>true,'mode'=>demopress_mode(),'wordpress'=>get_bloginfo('version'),'home'=>home_url('/'),'theme'=>get_stylesheet()];}]);});
function demopress_headers($type,$name){while(ob_get_level())@ob_end_clean();nocache_headers();header_remove('Content-Type');header('Content-Type: '.$type);header('Content-Disposition: attachment; filename="'.$name.'"');header('X-DemoPress-Export-Protocol: 2');}
function demopress_tmp($n){return trailingslashit(get_temp_dir()).'demopress-'.$n.'-'.wp_generate_password(12,false,false).'.tar.gz';}
function demopress_tar($args){$cmd='tar';foreach($args as $a)$cmd.=' '.escapeshellarg($a);exec($cmd.' 2>&1',$out,$code);if($code!==0)throw new RuntimeException('tar failed: '.implode("
",$out));}
function demopress_content(){ $f=demopress_tmp('content');demopress_tar(['-czf',$f,'-C',WP_CONTENT_DIR,'--exclude=plugins/demopress-agent','plugins','themes']);return $f;}function demopress_uploads(){ $u=wp_upload_dir();if(!is_dir($u['basedir']))return null;$entries=array_diff(scandir($u['basedir'])?:[],['.','..']);if(!$entries)return null;$f=demopress_tmp('uploads');demopress_tar(['-czf',$f,'-C',$u['basedir'],'.']);return $f;}
function demopress_stream_db(){global $wpdb;demopress_headers('application/sql; charset=utf-8','database.sql');echo "SET FOREIGN_KEY_CHECKS=0;
";foreach($wpdb->get_col('SHOW TABLES') as $table){$c=$wpdb->get_row("SHOW CREATE TABLE `$table`",ARRAY_N);if(!$c)continue;echo "DROP TABLE IF EXISTS `$table`;
{$c[1]};
";$offset=0;do{$rows=$wpdb->get_results("SELECT * FROM `$table` LIMIT 500 OFFSET ".intval($offset),ARRAY_A);foreach($rows as $row){$vals=array_map(function($v)use($wpdb){return is_null($v)?'NULL':"'".$wpdb->_real_escape($v)."'";},array_values($row));echo "INSERT INTO `$table` VALUES(".implode(',',$vals).");
";}$offset+=count($rows);}while(count($rows)===500);}echo "SET FOREIGN_KEY_CHECKS=1;
";}
add_action('template_redirect',function(){if(empty($_GET['demopress_export']))return;$type=sanitize_key(wp_unslash($_GET['demopress_export']));if(!demopress_template_mode()||!demopress_direct_auth()){status_header(401);exit('Unauthorized');}@set_time_limit(0);if($type==='database'){demopress_stream_db();exit;}if($type==='content'||$type==='uploads'){$f=$type==='content'?demopress_content():demopress_uploads();if(!$f){status_header(204);exit;}demopress_headers('application/gzip',$type.'.tar.gz');header('Content-Length: '.filesize($f));readfile($f);@unlink($f);exit;}status_header(400);exit('Unknown export type');},-1000);
add_action('init',function(){if(empty($_GET['demopress_demo_login'])||demopress_mode()!=='demo')return;$token=(string)wp_unslash($_GET['demopress_demo_login']);$user=get_user_by('login',getenv('DEMOPRESS_DEMO_USER')?:'');$expected=getenv('DEMOPRESS_DEMO_PASSWORD')?:'';if(!$user||!$expected||!hash_equals($expected,$token))return;wp_set_current_user($user->ID);wp_set_auth_cookie($user->ID,true,is_ssl());wp_safe_redirect(admin_url());exit;});
