const db=require('./database');
const snapshots=require('./snapshots');
const presets=require('./presets');
const settings=require('./settings');
const docker=require('./docker');
const config=require('./config');

function secs(d){return d.provision_finished_at&&d.provision_started_at?d.provision_finished_at-d.provision_started_at:0}
function safeRows(){try{return db.prepare("SELECT id,status,health_status,provision_stage,status_message,created_at,provision_started_at,provision_finished_at,demo_type,preset_slug FROM demos ORDER BY created_at DESC LIMIT 2000").all()}catch(_){return[]}}
async function summary(){
 const rows=safeRows(),publicRows=rows.filter(x=>(x.demo_type||'public')==='public'),now=Math.floor(Date.now()/1000),today=publicRows.filter(x=>x.created_at>now-86400),active=rows.filter(x=>['queued','provisioning','running','resetting'].includes(x.status)),completed=publicRows.filter(x=>['running','deleted','failed'].includes(x.status)),successful=completed.filter(x=>['running','deleted'].includes(x.status)),times=publicRows.map(secs).filter(Boolean),current=snapshots.current();
 let dockerOk=false,imageOk=false;
 try{await docker.ping();dockerOk=true}catch(_){}
 try{await docker.getImage(config.demoImage).inspect();imageOk=true}catch(_){}
 return {
  active:active.length,
  launchesToday:today.length,
  successRate:completed.length?Number((successful.length/completed.length*100).toFixed(1)):null,
  medianReady:times.length?times.sort((a,b)=>a-b)[Math.floor(times.length/2)]:null,
  capacity:settings.number('max_active_demos',config.maxDemos),
  snapshot:current?{version:current.version,validated:current.validation_status==='passed',size:current.size_bytes||0}:null,
  presets:presets.list({enabledOnly:true}).length,
  health:{launcher:true,docker:dockerOk,image:imageOk,template:Boolean(current),snapshot:Boolean(current&&current.validation_status==='passed')},
  recent:rows.slice(0,7).map(d=>({id:d.id,status:d.status,health:d.health_status||'unknown',stage:d.provision_stage||'',message:d.status_message||'',createdAt:d.created_at,type:d.demo_type||'public',preset:d.preset_slug||'default'}))
 };
}

const css=String.raw`
/* manager-polish-v2 */
body{background:#f5f5f3!important;color:#171717!important;--fg:#171717!important;--muted:#71717a!important;--line:#e5e5e2!important;--brand:#111!important;--panel:#fff!important;--panel-solid:#fff!important;--shadow:0 1px 2px rgba(0,0,0,.025),0 10px 32px rgba(0,0,0,.035)!important;--focus:0 0 0 3px rgba(17,17,17,.10)!important}
.manager-shell{grid-template-columns:268px minmax(0,1fr)!important;background:#f5f5f3!important}.manager-side{width:268px!important;background:#fff!important;border-right:1px solid #e7e7e4!important;padding:24px 16px 18px!important}.manager-brand{color:#111!important;font-size:14px!important;padding:3px 10px 25px!important;letter-spacing:.15em!important}.manager-brand span{color:#9a9a9f!important}.nav-label{color:#a1a1a7!important;font-size:10px!important;padding:0 10px 8px!important}.manager-nav a{color:#64646b!important;font-size:13px!important;padding:10px 11px!important;border-radius:10px!important;gap:11px!important}.manager-nav a:hover{background:#f4f4f2!important;color:#111!important}.manager-nav a.active{background:#111!important;color:#fff!important;box-shadow:0 1px 2px rgba(0,0,0,.12)!important}.nav-icon{width:21px!important;height:21px!important;display:grid!important;place-items:center!important;opacity:1!important}.nav-icon svg{width:17px;height:17px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.side-foot{border-top:1px solid #ececea!important}.side-foot a,.side-foot button{color:#77777e!important}.side-foot a:hover,.side-foot button:hover{color:#111!important;background:#f4f4f2!important}
.manager-main{background:#f5f5f3!important}.manager-top{background:rgba(245,245,243,.88)!important;border-bottom:1px solid #e7e7e4!important;backdrop-filter:blur(16px)!important}.manager-content{max-width:1420px!important;padding:34px 38px 70px!important}.manager-content h1{font-size:32px!important;letter-spacing:-.045em!important;margin:0 0 7px!important}.manager-content h2{letter-spacing:-.035em!important}.manager-content>.kpirow:first-child,.page-header{padding-bottom:22px!important;margin-bottom:4px!important;border-bottom:1px solid #e4e4e1!important;align-items:center!important}.sub{font-size:14px!important;line-height:1.55!important}.crumb{font-size:12px!important;color:#8a8a91!important;margin-bottom:17px!important}.crumb a{color:#55555c!important;text-decoration:none!important}
.card{background:#fff!important;border:1px solid #e6e6e3!important;border-radius:14px!important;box-shadow:var(--shadow)!important;padding:22px!important;backdrop-filter:none!important}.grid{gap:14px!important}.label{font-size:10px!important;letter-spacing:.13em!important;color:#8b8b92!important}.stat{font-size:34px!important;color:#181818!important}.value{color:#202020!important}.muted{color:#73737a!important}.btn{border-radius:9px!important;min-height:40px!important;padding:10px 15px!important;font-size:12px!important;box-shadow:none!important}.btn:not(.secondary):not(.red){background:#111!important;color:#fff!important}.btn.secondary{background:#fff!important;border-color:#dcdcd8!important;color:#292929!important}.btn.secondary:hover{background:#f4f4f2!important;border-color:#ccccca!important}.btn.red,.red{background:#fff!important;color:#a32a2a!important;border-color:#e6caca!important}.btn.mini{min-height:33px!important;padding:7px 10px!important;font-size:11px!important}.badge,.status-pill{display:inline-flex!important;align-items:center!important;gap:7px!important;border:1px solid #dfdfdc!important;background:#f8f8f6!important;color:#5f5f65!important;border-radius:999px!important;padding:6px 9px!important;font-size:11px!important;font-weight:750!important;line-height:1!important;white-space:nowrap!important}.badge:before,.status-pill:before{content:'';width:7px;height:7px;border-radius:50%;background:#a1a1a7;flex:0 0 auto}.badge.success,.status-success{background:#f2faf5!important;border-color:#cfe8d8!important;color:#257044!important}.badge.success:before,.status-success:before{background:#36a466!important}.badge.warn,.status-warn{background:#fff9ed!important;border-color:#eadab7!important;color:#8a641d!important}.badge.warn:before,.status-warn:before{background:#d59a2d!important}.badge.danger,.status-danger{background:#fff3f3!important;border-color:#e9cccc!important;color:#a33a3a!important}.badge.danger:before,.status-danger:before{background:#cf4e4e!important}.status-progress:before{background:#6b6b72!important;animation:dp-pulse 1.2s ease infinite}.success{color:#257044!important}.warn{color:#8a641d!important}.danger{color:#a33a3a!important}@keyframes dp-pulse{0%,100%{opacity:.35;transform:scale(.8)}50%{opacity:1;transform:scale(1.12)}}
.metric-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;margin-top:20px!important}.metric-grid .card{position:relative;overflow:hidden;margin:0!important;min-height:145px!important;padding:20px 21px!important}.metric-grid .card:after{content:'';position:absolute;left:21px;right:21px;bottom:16px;height:18px;opacity:.22;background:linear-gradient(155deg,transparent 0 16%,#202020 17% 20%,transparent 21% 31%,#202020 32% 35%,transparent 36% 45%,#202020 46% 49%,transparent 50% 62%,#202020 63% 66%,transparent 67%);clip-path:polygon(0 70%,12% 58%,25% 72%,38% 38%,51% 50%,66% 25%,80% 43%,100% 12%,100% 100%,0 100%)}.metric-grid .stat{margin-top:13px!important}.context-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.dashboard-panels{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.75fr);gap:14px;margin-top:15px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:15px}.panel-head h2{font-size:17px;margin:0!important}.recent-list,.health-list{display:grid;gap:2px}.recent-item,.health-item{display:grid;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid #efefec}.recent-item:last-child,.health-item:last-child{border-bottom:0}.recent-item{grid-template-columns:minmax(120px,1.3fr) auto auto}.recent-id{font:600 12px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;color:#29292d;text-decoration:none}.recent-meta{font-size:11px;color:#929298}.health-item{grid-template-columns:1fr auto}.health-name{font-size:12px;font-weight:700;color:#343439}.health-note{display:block;font-size:10px;color:#929298;font-weight:500;margin-top:2px}
.tablewrap{background:#fff!important;border:1px solid #e6e6e3!important;border-radius:14px!important;box-shadow:var(--shadow)!important;overflow:auto!important}table{border-collapse:collapse!important;width:100%!important}th{background:#fafaf8!important;color:#8c8c92!important;font-size:10px!important;text-transform:uppercase!important;letter-spacing:.09em!important;font-weight:800!important;padding:12px 14px!important;border-bottom:1px solid #e8e8e5!important}td{padding:13px 14px!important;border-bottom:1px solid #eeeeeb!important;font-size:12px!important;color:#414146!important}tr:last-child td{border-bottom:0!important}tbody tr:hover td{background:#fcfcfa!important}
input,select,textarea{background:#fff!important;color:#202024!important;border:1px solid #dcdcd8!important;border-radius:9px!important;min-height:43px!important}input:focus,select:focus,textarea:focus{border-color:#949499!important;box-shadow:0 0 0 3px rgba(17,17,17,.07)!important}.fieldhint{color:#929298!important}.notice{border-radius:10px!important}.terminal,.codeblock{border-radius:11px!important;background:#151517!important;border-color:#2d2d31!important;color:#e8e8e5!important}
.pipeline-card{margin:18px 0!important;padding:20px 22px!important}.pipeline{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin-top:19px}.pipe-step{position:relative;padding:30px 8px 0;text-align:center;color:#8d8d93;font-size:11px;font-weight:700}.pipe-step:before{content:'';position:absolute;top:7px;left:50%;width:12px;height:12px;border:2px solid #c9c9c5;background:#fff;border-radius:50%;transform:translateX(-50%);z-index:2}.pipe-step:not(:last-child):after{content:'';position:absolute;height:2px;background:#ddddda;top:13px;left:50%;width:100%;z-index:1}.pipe-step.done{color:#242428}.pipe-step.done:before{background:#111;border-color:#111}.pipe-step.done:not(:last-child):after{background:#111}.pipe-step.active:before{box-shadow:0 0 0 5px #ededeb;background:#111;border-color:#111}
.snapshot-cards{background:transparent!important;border:0!important;box-shadow:none!important;overflow:visible!important}.snapshot-cards table,.snapshot-cards tbody{display:block!important}.snapshot-cards tr:first-child{display:none!important}.snapshot-cards tr.snapshot-card{display:grid!important;grid-template-columns:1.35fr .85fr .65fr 1fr .65fr 1.8fr;align-items:center;gap:12px;background:#fff;border:1px solid #e4e4e1;border-radius:13px;margin:0 0 10px;padding:7px 8px;box-shadow:0 1px 2px rgba(0,0,0,.025)}.snapshot-cards tr.snapshot-card td{border:0!important;background:transparent!important;padding:12px!important}.snapshot-cards tr.snapshot-card.active-card{border-color:#aaa9a4;box-shadow:0 0 0 1px #d8d8d4,0 8px 30px rgba(0,0,0,.045)}
.preset-cards{background:transparent!important;border:0!important;box-shadow:none!important;overflow:visible!important}.preset-cards table,.preset-cards tbody{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:14px!important}.preset-cards tr:first-child{display:none!important}.preset-cards tr.preset-card{display:block!important;background:#fff;border:1px solid #e4e4e1;border-radius:14px;padding:20px;box-shadow:var(--shadow)}.preset-cards tr.preset-card td{display:block!important;border:0!important;padding:5px 0!important}.preset-cards tr.preset-card td:before{content:attr(data-label);display:block;font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:#99999f;font-weight:800;margin-bottom:3px}.preset-cards tr.preset-card td:first-child{font-size:18px!important;padding-bottom:13px!important;border-bottom:1px solid #efefec!important;margin-bottom:8px}.preset-cards tr.preset-card td:first-child:before{display:none}.preset-cards tr.preset-card td:last-child{padding-top:14px!important}.preset-cards .actions{display:flex!important}
.flash{border-radius:11px!important}.settings-shortcut{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:20px!important}.manager-version{display:flex;align-items:center;gap:7px;color:#a0a0a6;font-size:10px;padding:8px 3px 0}.manager-version i{width:6px;height:6px;border-radius:50%;background:#4aaa70}
@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.dashboard-panels{grid-template-columns:1fr}.snapshot-cards tr.snapshot-card{grid-template-columns:1fr 1fr 1fr}.preset-cards table,.preset-cards tbody{grid-template-columns:1fr!important}}
@media(max-width:820px){.manager-shell{display:block!important}.manager-side{position:relative!important;top:auto!important;width:100%!important;height:auto!important;z-index:30!important;border-right:0!important;border-bottom:1px solid #e6e6e3!important;padding:12px!important}.manager-brand{padding:5px 8px 11px!important}.manager-brand span{display:inline!important;margin-left:7px!important}.manager-nav{display:grid!important;grid-template-columns:minmax(0,1fr)!important;overflow:visible!important;gap:8px!important}.nav-group{display:flex!important;align-items:center!important;width:100%!important;min-width:0!important;margin:0!important;gap:4px!important;overflow-x:auto!important;overflow-y:hidden!important;padding:0 0 3px!important;scrollbar-width:thin!important}.nav-label{display:flex!important;align-items:center!important;align-self:stretch!important;flex:0 0 78px!important;padding:0 9px!important;font-size:9px!important;line-height:1.2!important;background:#f5f5f3!important;border-radius:9px!important;position:sticky!important;left:0!important;z-index:2!important}.manager-nav a{flex:0 0 auto!important;min-width:max-content!important;white-space:nowrap!important;margin:0!important}.manager-nav a>span:last-child{white-space:nowrap!important}.side-foot{display:none!important}.manager-content{padding:24px 16px 50px!important}.metric-grid{grid-template-columns:1fr 1fr!important}.preset-cards table,.preset-cards tbody{display:block!important}.snapshot-cards tr.snapshot-card{grid-template-columns:1fr!important}.snapshot-cards tr.snapshot-card td:before{content:attr(data-label);display:block;font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:#99999f;font-weight:800;margin-bottom:4px}}
@media(max-width:560px){.manager-brand span{display:block!important;margin:5px 0 0!important}.nav-label{flex-basis:68px!important;padding:0 7px!important}.manager-nav a{font-size:12px!important;padding:9px!important;gap:8px!important}.metric-grid{grid-template-columns:1fr!important}.manager-content h1{font-size:28px!important}.recent-item{grid-template-columns:1fr auto}.recent-meta{display:none}.pipeline{grid-template-columns:1fr!important}.pipe-step{text-align:left;padding:5px 0 5px 25px}.pipe-step:before{top:7px;left:6px}.pipe-step:not(:last-child):after{top:18px;left:6px;width:2px;height:100%}.settings-shortcut{display:block!important}.settings-shortcut .btn{margin-top:14px!important}}
`;

const js=String.raw`<script id="manager-polish-v2">(function(){
const path=location.pathname;
const icons={
 '/manage':'<svg viewBox="0 0 24 24"><path d="M4 11 12 4l8 7"/><path d="M6 10v10h12V10"/></svg>',
 '/manage/demos':'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/></svg>',
 '/manage/analytics':'<svg viewBox="0 0 24 24"><path d="M5 19V9M12 19V5M19 19v-7"/></svg>',
 '/manage/setup':'<svg viewBox="0 0 24 24"><path d="m12 3 2 4 4 .6-3 3 .7 4.4-3.7-2-3.7 2 .7-4.4-3-3L10 7z"/></svg>',
 '/manage/profile':'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-4 3-6 7-6s6.2 2 7 6"/></svg>',
 '/manage/template':'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>',
 '/manage/presets':'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="7" height="6" rx="1"/><rect x="13" y="5" width="7" height="6" rx="1"/><rect x="4" y="13" width="16" height="6" rx="1"/></svg>',
 '/manage/settings/visitor-capture':'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h10"/><circle cx="17" cy="18" r="3"/></svg>',
 '/manage/settings/demo-experience':'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="12" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
 '/manage/diagnostics':'<svg viewBox="0 0 24 24"><path d="M4 12h4l2-5 4 10 2-5h4"/></svg>',
 '/manage/system':'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></svg>',
 '/manage/settings':'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.5 1a7 7 0 0 0-1.7-1L14.4 3h-4.8l-.4 3.1a7 7 0 0 0-1.7 1l-2.5-1-2 3.4L5 11a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.5-1a7 7 0 0 0 1.7 1l.4 3.1h4.8l.4-3.1a7 7 0 0 0 1.7-1l2.5 1 2-3.4L19 13a7 7 0 0 0 0-1z"/></svg>'
};
function addNav(){const groups=[...document.querySelectorAll('.nav-group')],configure=groups.find(g=>/configure/i.test(g.querySelector('.nav-label')?.textContent||''));if(configure){const existing=new Set([...configure.querySelectorAll('a')].map(a=>a.getAttribute('href')));[['/manage/presets','Presets'],['/manage/settings/demo-experience','Demo Experience']].forEach(([href,text])=>{if(existing.has(href))return;const a=document.createElement('a');a.href=href;a.innerHTML='<span class="nav-icon"></span><span>'+text+'</span>';configure.appendChild(a);});}document.querySelectorAll('.manager-nav a').forEach(a=>{const h=a.getAttribute('href'),i=a.querySelector('.nav-icon');if(i&&icons[h])i.innerHTML=icons[h];const active=h==='/manage'?(path==='/manage'||path==='/manage/'):path===h||path.startsWith(h+'/');a.classList.toggle('active',active);});const foot=document.querySelector('.side-foot');if(foot&&!foot.querySelector('.manager-version'))foot.insertAdjacentHTML('beforeend','<div class="manager-version"><i></i> DemoPress Manager</div>');}
function pillFor(text){const s=String(text||'').trim().toLowerCase();if(['running','ready','healthy','verified','validated','active','enabled','passed','operational','connected','available'].includes(s))return'status-success';if(['failed','degraded','unavailable','disabled','error','deleted'].includes(s))return'status-danger';if(['queued','provisioning','resetting','testing','untested','unknown','pending'].includes(s))return s==='queued'||s==='provisioning'||s==='resetting'||s==='testing'?'status-progress status-warn':'status-warn';return'';}
function statusify(root=document){root.querySelectorAll('td').forEach(td=>{if(td.children.length)return;const c=pillFor(td.textContent);if(!c)return;const t=td.textContent.trim();td.innerHTML='<span class="status-pill '+c+'">'+t+'</span>';});}
function pageHeader(){const first=document.querySelector('.manager-content>.kpirow:first-child');if(first)first.classList.add('page-header');}
function fmtAge(ts){const s=Math.max(0,Math.floor(Date.now()/1000)-Number(ts||0));if(s<60)return s+'s';if(s<3600)return Math.floor(s/60)+'m';if(s<86400)return Math.floor(s/3600)+'h';return Math.floor(s/86400)+'d';}
function statusClass(s){return pillFor(s)||'';}
function dashboard(){if(!(path==='/manage'||path==='/manage/'))return;const content=document.querySelector('.manager-content'),grids=[...content.querySelectorAll(':scope>.grid')];if(grids[0]){grids[0].classList.add('metric-grid');if(grids[1]){const avg=grids[1].querySelector('.card');if(avg)grids[0].appendChild(avg);grids[1].classList.add('context-grid');}}fetch('/manage/ui-summary.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>{if(!content||content.querySelector('.dashboard-panels'))return;const actions=[...content.querySelectorAll(':scope>.actions')].pop();const health=[['Launcher',x.health.launcher,'Manager API responding'],['Docker',x.health.docker,'Docker daemon connection'],['Runtime image',x.health.image,'Disposable WordPress image'],['Template',x.health.template,'Active golden snapshot'],['Snapshot validation',x.health.snapshot,'Strict readiness validated']];const html='<div class="dashboard-panels"><section class="card"><div class="panel-head"><h2>Recent demos</h2><a class="btn mini secondary" href="/manage/demos">View all</a></div><div class="recent-list">'+(x.recent.length?x.recent.map(d=>'<div class="recent-item"><a class="recent-id" href="/manage/demos/'+encodeURIComponent(d.id)+'">'+d.id+'</a><span class="status-pill '+statusClass(d.status)+'">'+d.status+'</span><span class="recent-meta">'+fmtAge(d.createdAt)+' ago · '+d.preset+'</span></div>').join(''):'<div class="muted">No demos yet.</div>')+'</div></section><section class="card"><div class="panel-head"><h2>System health</h2><span class="status-pill '+(health.every(h=>h[1])?'status-success':'status-warn')+'">'+(health.every(h=>h[1])?'Healthy':'Attention')+'</span></div><div class="health-list">'+health.map(h=>'<div class="health-item"><div><span class="health-name">'+h[0]+'</span><span class="health-note">'+h[2]+'</span></div><span class="status-pill '+(h[1]?'status-success':'status-danger')+'">'+(h[1]?'Ready':'Check')+'</span></div>').join('')+'</div></section></div>';(actions||grids[1]||grids[0]).insertAdjacentHTML('afterend',html);}).catch(()=>{});}
function template(){if(!path.startsWith('/manage/template'))return;const content=document.querySelector('.manager-content'),table=[...content.querySelectorAll('table')].find(t=>[...t.querySelectorAll('th')].some(x=>x.textContent.trim()==='Version'));if(!table)return;const rows=[...table.querySelectorAll('tr')].slice(1),hasValidated=rows.some(r=>/Validated/i.test(r.textContent)),hasActive=rows.some(r=>/ACTIVE/i.test(r.textContent));if(!content.querySelector('.pipeline-card')){const firstCard=content.querySelector('.card');const pipe='<section class="card pipeline-card"><div class="panel-head"><div><div class="label">Snapshot pipeline</div><h2 style="margin:5px 0 0">Release confidence at a glance</h2></div><span class="badge '+(hasActive?'success':'warn')+'">'+(hasActive?'Production ready':'Action required')+'</span></div><div class="pipeline"><div class="pipe-step done">Exported</div><div class="pipe-step '+(hasValidated?'done active':'active')+'">Validated</div><div class="pipe-step '+(hasValidated?'done':'')+'">Ready</div><div class="pipe-step '+(hasActive?'done active':'')+'">Active</div></div></section>';(firstCard||content.querySelector('.grid')).insertAdjacentHTML('beforebegin',pipe);}const wrap=table.closest('.tablewrap');if(wrap)wrap.classList.add('snapshot-cards');const heads=[...table.querySelectorAll('tr:first-child th')].map(h=>h.textContent.trim());rows.forEach(r=>{r.classList.add('snapshot-card');if(/ACTIVE/i.test(r.textContent))r.classList.add('active-card');[...r.children].forEach((td,i)=>td.dataset.label=heads[i]||'');});}
function presetCards(){if(path!=='/manage/presets')return;const table=document.querySelector('.manager-content table');if(!table)return;const wrap=table.closest('.tablewrap');if(wrap)wrap.classList.add('preset-cards');const heads=[...table.querySelectorAll('tr:first-child th')].map(h=>h.textContent.trim());[...table.querySelectorAll('tr')].slice(1).forEach(r=>{r.classList.add('preset-card');[...r.children].forEach((td,i)=>td.dataset.label=heads[i]||'');});}
addNav();pageHeader();statusify();dashboard();template();presetCards();
})();</script>`;

function inject(body){if(typeof body!=='string'||!body.includes('DemoPress Manager')||body.includes('manager-polish-v2'))return body;let out=body.replace('</head>',`<style>${css}</style></head>`);out=out.replace('</body>',`${js}</body>`);return out;}

async function middleware(req,res,next){
 if(req.path==='/ui-summary.json'){
  try{res.set('Cache-Control','no-store');return res.json(await summary())}catch(e){return res.status(500).json({error:'Unable to build Manager summary'})}
 }
 const send=res.send.bind(res);
 res.send=function(body){return send(inject(body))};
 next();
}

module.exports=middleware;
