const db=require('./database');
const snapshots=require('./snapshots');
const config=require('./config');
const profile=require('./profile');

function cleanSlug(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)}
function list({enabledOnly=false}={}){return db.prepare(`SELECT * FROM presets ${enabledOnly?'WHERE is_enabled=1':''} ORDER BY is_default DESC,name COLLATE NOCASE`).all()}
function get(slug){return db.prepare('SELECT * FROM presets WHERE slug=?').get(cleanSlug(slug))}
function defaultPreset(){return db.prepare('SELECT * FROM presets WHERE is_default=1 AND is_enabled=1 ORDER BY updated_at DESC LIMIT 1').get()||db.prepare("SELECT * FROM presets WHERE slug='default' AND is_enabled=1 LIMIT 1").get()||db.prepare('SELECT * FROM presets WHERE is_enabled=1 ORDER BY updated_at DESC LIMIT 1').get()||null}
function publicPreset(slug){const p=get(slug||'');return p&&p.is_enabled?p:null}
function parsePlugins(p){try{const x=JSON.parse(p.required_plugins_json||'[]');return Array.isArray(x)?x.filter(Boolean):[]}catch(_){return[]}}
function effective(p){if(!p)p=defaultPreset();const snap=p&&p.snapshot_version?snapshots.get(p.snapshot_version):snapshots.current();return{...p,snapshot:snap,requiredPlugins:parsePlugins(p).length?parsePlugins(p):(profile.requiredPlugins||[]),requiredTheme:p&&p.required_theme?p.required_theme:(profile.requiredTheme||''),idleLifetime:Number(p&&p.idle_lifetime)||null,maxLifetime:Number(p&&p.max_lifetime)||null,startPath:normaliseStartPath(p&&p.start_path)}}
function normaliseStartPath(v){let s=String(v||'/wp-admin/').trim();if(!s.startsWith('/')||s.startsWith('//'))return'/wp-admin/';if(/^\/\//.test(s))return'/wp-admin/';return s.slice(0,500)||'/wp-admin/'}
function save(input){const slug=cleanSlug(input.slug);if(!slug)throw new Error('Preset slug is required');const name=String(input.name||'').trim().slice(0,120);if(!name)throw new Error('Preset name is required');const snapshotVersion=String(input.snapshot_version||'').trim()||null;if(snapshotVersion){const s=snapshots.get(snapshotVersion);if(!s)throw new Error('Selected snapshot does not exist');if(s.validation_status!=='passed')throw new Error('Preset snapshots must pass validation before use')}let plugins=[];if(Array.isArray(input.required_plugins))plugins=input.required_plugins;else if(typeof input.required_plugins==='string')plugins=input.required_plugins.split(/[,\n]/);plugins=plugins.map(x=>String(x).trim()).filter(Boolean).slice(0,100);const now=Math.floor(Date.now()/1000),existing=get(slug),isDefault=input.is_default?1:0,isEnabled=input.is_enabled===false?0:1;if(isDefault&&!isEnabled)throw new Error('The default preset must be enabled');if(existing&&existing.is_default&&!isDefault){const replacement=db.prepare('SELECT slug FROM presets WHERE is_default=1 AND slug!=? AND is_enabled=1 LIMIT 1').get(slug);if(!replacement)throw new Error('Choose another enabled preset as the default before removing default status from this preset')}const tx=db.transaction(()=>{if(isDefault)db.prepare('UPDATE presets SET is_default=0 WHERE slug!=?').run(slug);db.prepare(`INSERT INTO presets(slug,name,description,snapshot_version,required_plugins_json,required_theme,start_path,idle_lifetime,max_lifetime,is_enabled,is_default,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,snapshot_version=excluded.snapshot_version,required_plugins_json=excluded.required_plugins_json,required_theme=excluded.required_theme,start_path=excluded.start_path,idle_lifetime=excluded.idle_lifetime,max_lifetime=excluded.max_lifetime,is_enabled=excluded.is_enabled,is_default=excluded.is_default,updated_at=excluded.updated_at`).run(slug,name,String(input.description||'').trim().slice(0,500),snapshotVersion,JSON.stringify(plugins),String(input.required_theme||'').trim().slice(0,160),normaliseStartPath(input.start_path),Number(input.idle_lifetime)||null,Number(input.max_lifetime)||null,isEnabled,isDefault,existing?existing.created_at:now,now)});tx();return get(slug)}
function remove(slug){slug=cleanSlug(slug);const p=get(slug);if(!p)return false;if(p.is_default||slug==='default')throw new Error('The default preset cannot be deleted');const used=db.prepare("SELECT COUNT(*) c FROM demos WHERE preset_slug=? AND status IN ('queued','provisioning','running','resetting')").get(slug).c;if(used)throw new Error('Preset is currently in use by an active demo');db.prepare('DELETE FROM presets WHERE slug=?').run(slug);return true}
module.exports={list,get,defaultPreset,publicPreset,effective,save,remove,cleanSlug,normaliseStartPath};
