const express=require('express');
const presets=require('./presets');
const snapshots=require('./snapshots');
const {adminPage}=require('./ui');
const {esc}=require('./helpers');
const {managerCsrf}=require('./security');
const r=express.Router();
r.use(managerCsrf);

function snapshotOptions(selected){return snapshots.list().filter(s=>s.validation_status==='passed').map(s=>`<option value="${esc(s.version)}" ${selected===s.version?'selected':''}>${esc(s.version)}${s.is_current?' · active':''}</option>`).join('')}
function form(p={}){const plugins=(()=>{try{return JSON.parse(p.required_plugins_json||'[]').join('\n')}catch(_){return''}})();return `<form method="post" action="/manage/presets/save"><div class="formgrid"><label>Preset name<input name="name" required maxlength="120" value="${esc(p.name||'')}"><span class="fieldhint">Visitor-facing name.</span></label><label>Slug<input name="slug" required maxlength="60" pattern="[a-z0-9_-]+" value="${esc(p.slug||'')}"><span class="fieldhint">Used as ?preset=slug. Lowercase letters, numbers, _ and - only.</span></label><label>Validated snapshot<select name="snapshot_version"><option value="">Use active snapshot</option>${snapshotOptions(p.snapshot_version||'')}</select></label><label>Start path<input name="start_path" value="${esc(p.start_path||'/wp-admin/')}"><span class="fieldhint">Safe local path opened by the one-click Admin action.</span></label><label>Idle lifetime (seconds)<input type="number" min="60" name="idle_lifetime" value="${esc(p.idle_lifetime||'')}"><span class="fieldhint">Blank uses the global setting.</span></label><label>Maximum lifetime (seconds)<input type="number" min="60" name="max_lifetime" value="${esc(p.max_lifetime||'')}"><span class="fieldhint">Blank uses the global setting.</span></label><label>Required theme<input name="required_theme" value="${esc(p.required_theme||'')}"><span class="fieldhint">Blank inherits the product profile.</span></label><label>Enabled<select name="is_enabled"><option value="1" ${p.is_enabled!==0?'selected':''}>Enabled</option><option value="0" ${p.is_enabled===0?'selected':''}>Disabled</option></select></label></div><label>Description<textarea name="description" maxlength="500">${esc(p.description||'')}</textarea></label><label>Required plugins<textarea name="required_plugins" placeholder="plugin-folder/plugin.php, one per line">${esc(plugins)}</textarea><span class="fieldhint">Blank inherits required plugins from the product profile.</span></label><label style="display:flex;gap:9px;align-items:center"><input style="width:auto;margin:0" type="checkbox" name="is_default" value="1" ${p.is_default?'checked':''}> Make this the default public preset</label><div class="actions"><button class="btn" type="submit">Save preset</button><a class="btn secondary" href="/manage/presets">Cancel</a></div></form>`}

r.get('/presets',(req,res)=>{const list=presets.list();res.send(adminPage('Presets',`<div class="crumb">Manager / Presets</div><div class="kpirow"><div><h1>Demo Presets</h1><div class="sub">Offer multiple product/demo configurations from one DemoPress installation. Existing installations use the Default preset automatically.</div></div><a class="btn" href="/manage/presets/new">New preset</a></div><div class="tablewrap" style="margin-top:22px"><table><tr><th>Name</th><th>Slug</th><th>Snapshot</th><th>Start</th><th>State</th><th>Actions</th></tr>${list.map(p=>`<tr><td><strong>${esc(p.name)}</strong>${p.description?`<div class="muted">${esc(p.description)}</div>`:''}</td><td><code>${esc(p.slug)}</code></td><td>${esc(p.snapshot_version||'Active snapshot')}</td><td><code>${esc(p.start_path||'/wp-admin/')}</code></td><td>${p.is_default?'<span class="badge success">Default</span> ':''}${p.is_enabled?'<span class="badge">Enabled</span>':'<span class="badge danger">Disabled</span>'}</td><td><div class="actions" style="margin:0"><a class="btn mini secondary" href="/manage/presets/${esc(p.slug)}">Edit</a><a class="btn mini secondary" target="_blank" rel="noopener" href="/?preset=${encodeURIComponent(p.slug)}">Preview launcher</a>${!p.is_default&&p.slug!=='default'?`<form method="post" action="/manage/presets/${esc(p.slug)}/delete"><button class="btn mini red" type="submit">Delete</button></form>`:''}</div></td></tr>`).join('')}</table></div>`, 'presets'))});
r.get('/presets/new',(req,res)=>res.send(adminPage('New preset',`<div class="crumb"><a href="/manage/presets">Presets</a> / New</div><h1>New Demo Preset</h1>${form({is_enabled:1,start_path:'/wp-admin/'})}`,'presets')));
r.get('/presets/:slug',(req,res)=>{const p=presets.get(req.params.slug);if(!p)return res.status(404).send(adminPage('Not found','<h1>Preset not found</h1>','presets'));res.send(adminPage(`Preset · ${p.name}`,`<div class="crumb"><a href="/manage/presets">Presets</a> / ${esc(p.name)}</div><h1>${esc(p.name)}</h1>${form(p)}`,'presets'))});
r.post('/presets/save',(req,res)=>{try{presets.save({slug:req.body.slug,name:req.body.name,description:req.body.description,snapshot_version:req.body.snapshot_version,required_plugins:req.body.required_plugins,required_theme:req.body.required_theme,start_path:req.body.start_path,idle_lifetime:req.body.idle_lifetime,max_lifetime:req.body.max_lifetime,is_enabled:req.body.is_enabled==='1',is_default:req.body.is_default==='1'});res.redirect('/manage/presets?saved='+encodeURIComponent('Preset saved'))}catch(e){res.status(400).send(adminPage('Preset not saved',`<h1>Preset not saved</h1><div class="notice">${esc(e.message)}</div><a class="btn secondary" href="/manage/presets">Back to presets</a>`,'presets'))}});
r.post('/presets/:slug/delete',(req,res)=>{try{presets.remove(req.params.slug);res.redirect('/manage/presets?saved='+encodeURIComponent('Preset deleted'))}catch(e){res.status(400).send(adminPage('Preset not deleted',`<h1>Preset not deleted</h1><div class="notice">${esc(e.message)}</div><a class="btn secondary" href="/manage/presets">Back to presets</a>`,'presets'))}});
module.exports=r;
