const fs=require("fs"),path=require("path"),{Readable}=require("stream"),{pipeline}=require("stream/promises");const config=require("./config"),db=require("./database"),profile=require("./profile");fs.mkdirSync(config.snapshotRoot,{recursive:true});
function get(v){return db.prepare("SELECT * FROM snapshots WHERE version=?").get(v)}function current(){return db.prepare("SELECT * FROM snapshots WHERE is_current=1 ORDER BY created_at DESC LIMIT 1").get()}function list(){return db.prepare("SELECT * FROM snapshots ORDER BY created_at DESC").all()}
function setCurrent(v,{force=false}={}){const s=get(v);if(!s)throw new Error("Snapshot not found");if(!force&&s.validation_status!=="passed")throw new Error("Snapshot must pass an isolated validation test before it can become active");const t=db.transaction(()=>{db.prepare("UPDATE snapshots SET is_current=0").run();db.prepare("UPDATE snapshots SET is_current=1 WHERE version=?").run(v);db.prepare("UPDATE presets SET snapshot_version=?,updated_at=? WHERE slug='default'").run(v,Math.floor(Date.now()/1000))});t();return get(v)}
function markValidation(v,status,{demoId=null,error=null}={}){if(!get(v))return;db.prepare("UPDATE snapshots SET validation_status=?,validated_at=?,validation_demo_id=?,validation_error=? WHERE version=?").run(status,status==="passed"?Math.floor(Date.now()/1000):null,demoId,error,v)}
function remove(v){const s=get(v);if(!s)return false;if(s.is_current)throw new Error("The active snapshot cannot be deleted");const refs=db.prepare("SELECT slug,name FROM presets WHERE snapshot_version=?").all(v);if(refs.length)throw new Error(`Snapshot is referenced by preset${refs.length===1?'':'s'}: ${refs.map(x=>x.name||x.slug).join(', ')}. Move those presets to another validated snapshot first.`);fs.rmSync(s.path,{recursive:true,force:true});db.prepare("DELETE FROM snapshots WHERE version=?").run(v);return true}
const headers=()=>({"X-DemoPress-Template-Token":config.templateToken,"Accept":"application/json","Cache-Control":"no-cache"});
function isRedirect(status){return status>=300&&status<400}
async function requestJson(url,ep){const r=await fetch(url,{headers:headers(),redirect:"manual",signal:AbortSignal.timeout(30000)});const text=await r.text(),type=String(r.headers.get("content-type")||"");if(isRedirect(r.status))return{ok:false,status:r.status,text,type,url,redirect:true,location:r.headers.get("location")||""};if(!r.ok)return{ok:false,status:r.status,text,type,url};if(!type.toLowerCase().includes("application/json"))return{ok:false,status:r.status,text,type,url};try{return{ok:true,data:JSON.parse(text),status:r.status,type,url}}catch(e){return{ok:false,status:r.status,text,type,url,error:`invalid JSON: ${e.message}`}}}
function apiError(ep,result,label){if(result.redirect)return new Error(`Template API ${ep} ${label} route returned redirect ${result.status}${result.location?` to ${result.location}`:""}. Authenticated DemoPress requests do not follow redirects so the template secret cannot be forwarded to another endpoint. Check TEMPLATE_DOMAIN/canonical WordPress URL.`);const detail=(result.text||"").slice(0,500),looksHtml=/^\s*<!doctype|^\s*<html/i.test(result.text||"");return new Error(`Template API ${ep} ${label} route failed (${result.status||0}; ${looksHtml?'HTML':result.type||'unknown content type'})${detail?`. Response: ${detail}`:""}`)}
async function api(ep){const pretty=`https://${config.templateDomain}/wp-json/demopress-agent/v1/${ep}`;const fallback=`https://${config.templateDomain}/?rest_route=${encodeURIComponent(`/demopress-agent/v1/${ep}`)}`;const first=await requestJson(pretty,ep);if(first.ok)return first.data;if(first.status===401||first.status===403||first.redirect)throw apiError(ep,first,"pretty");const second=await requestJson(fallback,ep);if(second.ok)return second.data;throw apiError(ep,second,"fallback")}
async function validate(){const inv=await api("status"),active=new Set((inv.plugins||[]).filter(p=>p.active).map(p=>p.file));const checks={template_mode:inv.mode==="template",wordpress:!!inv.wordpress,export_protocol:Number(inv.exportProtocol||0)>=2,required_plugins:(profile.requiredPlugins||[]).every(x=>active.has(x)),required_theme:!profile.requiredTheme||inv.activeTheme===profile.requiredTheme,db:!!inv.db};return{ok:!Object.values(checks).includes(false),checks,inventory:inv,profile:{productName:profile.productName,requiredPlugins:profile.requiredPlugins||[],requiredTheme:profile.requiredTheme||""}}}
async function status(){return api("status")}
async function dl(type,dest,required=true){const url=`https://${config.templateDomain}/?demopress_export=${encodeURIComponent(type)}`;const r=await fetch(url,{headers:headers(),redirect:"manual",signal:AbortSignal.timeout(900000)});if(isRedirect(r.status))throw new Error(`Template ${type} export returned redirect ${r.status}. Authenticated exports do not follow redirects; check TEMPLATE_DOMAIN and the canonical template URL.`);if(r.status===204&&!required)return{present:false,bytes:0};if(!r.ok)throw new Error(`Template ${type} export failed (${r.status}): ${(await r.text()).slice(0,500)}`);const part=dest+".part";await pipeline(Readable.fromWeb(r.body),fs.createWriteStream(part));const st=fs.statSync(part);if(!st.size)throw new Error(`${type} export empty`);fs.renameSync(part,dest);return{present:true,bytes:st.size}}
function version(){const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}.${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`}
async function publish(){const validation=await validate();if(!validation.ok)throw new Error(`Template validation failed: ${JSON.stringify(validation.checks)}`);const v=version(),dest=path.join(config.snapshotRoot,v);fs.mkdirSync(dest,{recursive:true});try{const database=await dl("database",path.join(dest,"database.sql"),true),content=await dl("content",path.join(dest,"content.tar.gz"),true),uploads=await dl("uploads",path.join(dest,"uploads.tar.gz"),false);const manifest={version:v,createdAt:Date.now(),exportProtocol:2,validation,template:validation.inventory,files:{database,content,uploads}};fs.writeFileSync(path.join(dest,"manifest.json"),JSON.stringify(manifest,null,2));const size=database.bytes+content.bytes+uploads.bytes;db.prepare("INSERT INTO snapshots(version,created_at,path,size_bytes,is_current,manifest_json,validation_status) VALUES(?,?,?,?,0,?,'untested')").run(v,Math.floor(Date.now()/1000),dest,size,JSON.stringify(manifest));for(const s of list().slice(config.maxSnapshots)){if(!s.is_current){try{remove(s.version)}catch(_){}}}return get(v)}catch(e){fs.rmSync(dest,{recursive:true,force:true});throw e}}
module.exports={get,current,list,setCurrent,markValidation,remove,validate,status,publish};
